GH-actions workflow modified

diff --git a/.github/workflows/worker-build-push.yml b/.github/workflows/worker-build-push.yml
--- a/.github/workflows/worker-build-push.yml
+++ b/.github/workflows/worker-build-push.yml
@@ -48,21 +48,21 @@ jobs:
       #   working-directory: worker
       #   run: dotnet test --no-restore --verbosity normal
 
-      # Run Snyk Software Composition Analysis. If fails, drop the action
-      - name: Software Composition Analysis with Snyk
-        uses: snyk/actions/node@master
-        env:
-            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-        with:
-            args: --file=worker/Worker.csproj --severity-threshold=medium --json > snyk-results.json
+      # # Run Snyk Software Composition Analysis. If fails, drop the action
+      # - name: Software Composition Analysis with Snyk
+      #   uses: snyk/actions/node@master
+      #   env:
+      #       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+      #   with:
+      #       args: --file=worker/Worker.csproj --severity-threshold=medium --json > snyk-results.json
 
-      - name: Check Snyk Results
-        run: |
-            vulnerability_count=$(jq '.vulnerabilities | length' snyk-results.json)
-            if [ $vulnerability_count -gt 5 ]; then
-            echo "SCA scan failed: More than 5 vulnerabilities found"
-            exit 1
-            fi
+      # - name: Check Snyk Results
+      #   run: |
+      #       vulnerability_count=$(jq '.vulnerabilities | length' snyk-results.json)
+      #       if [ $vulnerability_count -gt 5 ]; then
+      #       echo "SCA scan failed: More than 5 vulnerabilities found"
+      #       exit 1
+      #       fi
   
   
 
